version: '3.8'

services:
  db:
    image: mysql:8.0
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$MYSQL_ROOT_PASSWORD
      - MYSQL_DATABASE=$MYSQL_DATABASE
    ports:
      - $MYSQL_LOCAL_PORT:$MYSQL_DOCKER_PORT
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro

  app:
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - "80:$NODE_LOCAL_PORT"
    environment:
      - DB_HOST=db
      - DB_USER=$MYSQL_USER
      - DB_PASSWORD=$MYSQL_ROOT_PASSWORD
      - DB_NAME=$MYSQL_DATABASE
    depends_on:
      - db

volumes:
  db_data:
